### ISSUE TITLE
update web3?

### ISSUE THREAD

**Issue by brentkirkland** [trufflesuite/truffle-contract#13]
I get the following error:

```
W20170318-19:13:52.639(-7)? (STDERR) /home/brentkirkland/.meteor/packages/meteor-tool/.1.4.3_2.1r6il64++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170318-19:13:52.639(-7)? (STDERR) 						throw(ex);
W20170318-19:13:52.640(-7)? (STDERR) 						^
W20170318-19:13:52.640(-7)? (STDERR) 
W20170318-19:13:52.640(-7)? (STDERR) ReferenceError: Npm is not defined
W20170318-19:13:52.640(-7)? (STDERR)     at Object.<anonymous> (/home/brentkirkland/portal/node_modules/truffle-contract/node_modules/web3/lib/web3/httpprovider.js:34:22)
W20170318-19:13:52.640(-7)? (STDERR)     at Module._compile (module.js:409:26)
W20170318-19:13:52.640(-7)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170318-19:13:52.640(-7)? (STDERR)     at Module.load (module.js:343:32)
W20170318-19:13:52.640(-7)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170318-19:13:52.640(-7)? (STDERR)     at Module.require (module.js:353:17)
W20170318-19:13:52.641(-7)? (STDERR)     at require (internal/module.js:12:17)
W20170318-19:13:52.641(-7)? (STDERR)     at Object.<anonymous> (/home/brentkirkland/portal/node_modules/truffle-contract/node_modules/web3/lib/web3.js:42:20)
W20170318-19:13:52.641(-7)? (STDERR)     at Module._compile (module.js:409:26)
W20170318-19:13:52.641(-7)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

This error disappears when I update web3 to 0.18.2

**Comment by elenadimitrova** [comment]
Yes, we have the same here. I spoke with @tcoulter and he confirmed he'll update to 0.18 in next release.

**Comment by tcoulter** [comment]
This has been updated in truffle-contract 3.0.0. You can get this within Truffle v3.2.1. Cheers!
