### ISSUE TITLE
Contract.at() throws BigNumber Error for nonexistent contract address

### ISSUE THREAD

**Issue by bezalel** [trufflesuite/truffle-contract#5]
When checking if there exists contract on specific address in Ethereum network, "contract.js" throws BigNumber Error, so cannot check existence of contract on my deployment script code.

example code)
var contractAddress = '0xa916c2510261e45bc89a6fec7b68c55e3e1ba738'
MyToken.at(contractAddress).then()

Test environment : Truffle v3.1.1, Geth 1.5.9, Ropsten Test-net

I've done some debugging and found that 'code' parameter returned by geth node is '0x' in the case that contract is not existing on the requested address('0xa916c2510261e45bc89a6fec7b68c55e3e1ba738')

so additional checking condition(code == '0x') should be added to truffle-contract/contract.js:401
like below
```
            self.web3.eth.getCode(address, function(err, code) {
              if (err) return reject(err);

              if (!code || code == '0x' || new BigNumber(code).eq(0)) {
                return reject(new Error("Cannot create instance of " + self.contract_name + "; no code at address " + address));
              }

              accept(instance);
            });
```

---------------------------------------------------------------------
$$$ truffle migrate --network ropsten
Using network 'ropsten'.

Running migration: 1_initial_migration.js
Saving artifacts...
Running migration: 2_deploy_contracts.js
Starting Deployment on network ropsten
Saving artifacts...
/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/bignumber.js/bignumber.js:1209
            throw error;
            ^

BigNumber Error: new BigNumber() not a base 16 number: 
    at raise (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/bignumber.js/bignumber.js:1177:25)
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/bignumber.js/bignumber.js:1165:33
    at new BigNumber (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/bignumber.js/bignumber.js:212:28)
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/bignumber.js/bignumber.js:1160:48
    at new BigNumber (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/bignumber.js/bignumber.js:193:67)
    at Object.callback (**/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:401:28**)
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:142:25
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:89:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:119:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)

**Comment by LogvinovLeon** [comment]
This is probably fixed by #20 
Could you try with the newest version? (2.0.1)

**Comment by computertrousers** [comment]
I am already using v 2.0.1 and I have the same problem as original poster looks like the change to contract.js:401 hasn't made it into dist/truffle-contract*.js yet.  I have hacked my local copy for now but I guess the dist files need to be regenerated on the repo?

**Comment by steven0610** [comment]
I have the same problem, in Truffle v4.0.4 (core: 4.0.4).

**Comment by steven0610** [comment]
Did you resolve it ?

**Comment by steven0610** [comment]
Could u please help me .  Thank you verymuch

**Comment by EnchanterIO** [comment]
Any progress?
