### ISSUE TITLE
JSON stringify on a contract instance throws

### ISSUE THREAD

**Issue by pszabop** [trufflesuite/truffle-contract#52]
I'm attempting to print out a contract instance because the API docs don't list all the actual calls (I'm trying to figure out how to filter an event).

However, merely stringifying the instance throws, which is very odd.

The snippet:

        return AContract.deployed().then(function(instance) {
          console.log(JSON.stringify(instance, null, 2));   // throws.

throws:

```
     Error: Error: Method eth_protocolVersion not supported.
    at GethApiDouble.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:101870:16)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52856:18)
    at VmSubprovider.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:59803:12)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52856:18)
    at GethDefaults.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:101787:12)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52856:18)
    at FilterSubprovider.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:59362:7)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52856:18)
    at DelayedBlockFilter.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:101615:3)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52856:18)
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:37295:16)
      at RequestManager.send (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:224740:22)
      at Eth.get [as protocolVersion] (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:37413:62)
      at Object.stringify (<anonymous>)
      at test/acontract.js:10:24
      at process._tickCallback (internal/process/next_tick.js:109:7)
```
I'm using this truffle version:

```
root@0432330b10b9:/mnt# truffle version
Truffle v3.4.8 (core: 3.4.8)
Solidity v0.4.15 (solc-js)
```

**Comment by emacsvi** [comment]
solved this problem?

**Comment by pszabop** [comment]
nope, problem still there.

**Comment by szerintedmi** [comment]
I'm using this [stringifier](https://github.com/twada/stringifier)

**Comment by pszabop** [comment]
i'll try it, but really, JSON.stringify should never break...

**Comment by felipemmelo** [comment]
It worked for me: `JSON.stringify(Object.keys(instance))`
