### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by miguelmota** [trufflesuite/truffle-contract#57]
code

```js
const Contract = require('./contract.json')
const contract = truffleContract(Contract)
const provider = new Web3.providers.WebsocketProvider('ws://my_geth_websocket_uri')
contract.setProvider(provider)
const instance = await registry.deployed() // fails here
```

error

```
TypeError: Cannot read property 'apply' of undefined
    at Provider.sendAsync (/Users/mota/Sandbox/eth-events-db/node_modules/truffle-contract/contract.js:23:35)
    at RequestManager.sendAsync (/Users/mota/Sandbox/eth-events-db/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:80:19)
    at Object.get [as getNetwork] (/Users/mota/Sandbox/eth-events-db/node_modules/truffle-contract/node_modules/web3/lib/web3/property.js:116:33)
    at /Users/mota/Sandbox/eth-events-db/node_modules/truffle-contract/contract.js:477:27
    at Function.detectNetwork (/Users/mota/Sandbox/eth-events-db/node_modules/truffle-contract/contract.js:468:14)
    at Function.deployed (/Users/mota/Sandbox/eth-events-db/node_modules/truffle-contract/contract.js:416:19)
    at main (/Users/mota/Sandbox/eth-events-db/index.js:32:29)
    at Object.<anonymous> (/Users/mota/Sandbox/eth-events-db/index.js:115:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

Using web3 lib I have no issues. Issue occurs when using truffle-contract.

**Comment by szerintedmi** [comment]
I'm having the same issue with web3@1.0.0-beta.18 . It only happens with http provider, metamaskprovider works (more or less).
Have you tried with web@0.20.1? It works for me with that version

**Comment by 3psil0n** [comment]
Hey,
maybe someone can help me: Is this only an issue with newer versions? I cannot get truffle-contract working and I would like to use it.
Which versions do I need. 
Thank you in advance!

**Comment by szerintedmi** [comment]
A workaround from [here](https://github.com/trufflesuite/truffle-contract/issues/56#issuecomment-331084530):
```
let contract = Contract(artifacts);
contract.setProvider(web3.currentProvider);
//dirty hack for web3@1.0.0 support for localhost testrpc, see https://github.com/trufflesuite/truffle-contract/issues/56#issuecomment-331084530
if (typeof contract.currentProvider.sendAsync !== "function") {
  contract.currentProvider.sendAsync = function() {
    return contract.currentProvider.send.apply(
      contract.currentProvider, arguments
    );
  };
}
```

**Comment by hackingbeauty** [comment]
Having a similar issue here.

**Comment by hackingbeauty** [comment]
Hey everyone, I fixed this issue for myself.  I was passing the provider to ```setProvider()``` incorrectly.

This worked for me:

```
const VotingContract = TruffleContract(VotingContractJSON);
VotingContract.setProvider(provider.currentProvider);
```

Originally, I was just passing ```provider``` into ```setProvider()```.  Passing ```provider.currentProvider``` did the trick for me!

**Comment by lukehamilton** [comment]
@hackingbeauty thanks! this worked :)

**Comment by nikita-fuchs** [comment]
@szerintedmi **THANK YOU**. This was bugging me for days.

**Comment by robertsdotpm** [comment]
@szerintedmi Perfect fix, would use again

**Comment by lennartkramer1988** [comment]
@szerintedmi great workaround

Here is some boilerplate in case you want to hide this in a util/factory:
```
import Greeter from '../../contracts/Greeter.json';
import contract from 'truffle-contract';

export function buildGreeter(currentProvider) {
    const greeter = contract(Greeter);
    greeter.setProvider(currentProvider);
    return fixTruffleContractCompatibilityIssue(greeter);
}

// Workaround for a compatibility issue between web3@1.0.0-beta.29 and truffle-contract@3.0.3
// https://github.com/trufflesuite/truffle-contract/issues/57#issuecomment-331300494
function fixTruffleContractCompatibilityIssue(contract) {
    if (typeof contract.currentProvider.sendAsync !== "function") {
        contract.currentProvider.sendAsync = function() {
            return contract.currentProvider.send.apply(
                contract.currentProvider, arguments
            );
        };
    }
    return contract;
}
```

**Comment by dblockunity** [comment]
Thanks @szerintedmi,

This worked for me. I wrote some boilerplate below that is a full working script:

`const Web3 = require('web3');
const contract = require('truffle-contract');
const fs = require('fs');

const fileContents = fs.readFileSync('../build/contracts/MetaCoin.json', 'utf8');
const metacoinArtifacts = JSON.parse(fileContents);
const MetaCoin = contract(metacoinArtifacts);

var accounts;
var account;

const web3 = new Web3(new Web3.providers.HttpProvider("http://127.0.0.1:8545"));
MetaCoin.setProvider(web3.currentProvider);
if (typeof MetaCoin.currentProvider.sendAsync !== "function") {
    MetaCoin.currentProvider.sendAsync = function() {
        return MetaCoin.currentProvider.send.apply(
            MetaCoin.currentProvider, arguments
        );
    };
}

web3.eth.getAccounts(function(err, accs) {
    if (err != null) {
        console.error("There was an error fetching your accounts.");
        return;
    }
    if (accs.length == 0) {
        console.error("Couldn't get any accounts! Make sure your Ethereum client is configured correctly.");
        return;
    }
    accounts = accs;
    account = accounts[0];

    meta = MetaCoin.deployed().then(function(instance) {
        instance.getBalance.call(account, {from: account}).then(function(value) {
            console.log("Printing value: value of....");
            console.log(value.valueOf());
        });
    }).catch(function(e) {
        console.error(e);
    });
});`

**Comment by hqblock** [comment]
Thanks @dblockunity, it worked for me with a contract executing a transaction instead of a call. In that case the transaction consumes a lot of gas so I had to add the gas parameter : "{from: account, gas: 1000000}".
