### ISSUE TITLE
estimateGas not working on Kovan

### ISSUE THREAD

**Issue by TripleSpeeder** [trufflesuite/truffle-contract#67]
I have the same contract deployed on Ropsten, local testrpc and Kovan network. Calling estimateGas with the same parameters leads to "Transaction execution error" on Kovan, while it works fine on Ropsten and testrpc.

Contract source is StandingOrderFactory from https://github.com/TripleSpeeder/StandingOrderDapp/blob/master/contracts/StandingOrder.sol, deployed via truffle migrate.

### Testrpc (running `testrpc` without parameters):
```
truffle(development)> factory.createStandingOrder.estimateGas('0x8487814783F48cB7Da2358D767c5083d39Ba6794', 500000000, 600, 1508673563021, 'some label', {from: '0x8487814783F48cB7Da2358D767c5083d39Ba6794'})
676424
```
### Ropsten (running a local geth node with `geth --syncmode fast --testnet`)
```
truffle(Ropsten)> factory.createStandingOrder.estimateGas('0x8487814783F48cB7Da2358D767c5083d39Ba6794', 500000000, 600, 1508673563021, 'some label', {from: '0x8487814783F48cB7Da2358D767c5083d39Ba6794'})
672474
```
### Kovan (running local parity node with `parity --chain kovan`)
```
truffle(Kovan)> factory.createStandingOrder.estimateGas('0x8487814783F48cB7Da2358D767c5083d39Ba6794', 500000000, 600, 1508673563021, 'some label', {from: '0x8487814783F48cB7Da2358D767c5083d39Ba6794'})
Error: Transaction execution error.
    at Object.InvalidResponse (/home/michael/.node_modules/lib/node_modules/truffle/build/cli.bundled.js:37312:16)
    at /home/michael/.node_modules/lib/node_modules/truffle/build/cli.bundled.js:220420:36
    at /home/michael/.node_modules/lib/node_modules/truffle/build/cli.bundled.js:204149:9
    at XMLHttpRequest.request.onreadystatechange (/home/michael/.node_modules/lib/node_modules/truffle/build/cli.bundled.js:205574:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/michael/.node_modules/lib/node_modules/truffle/build/cli.bundled.js:73069:18)
    at XMLHttpRequest._setReadyState (/home/michael/.node_modules/lib/node_modules/truffle/build/cli.bundled.js:73359:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/michael/.node_modules/lib/node_modules/truffle/build/cli.bundled.js:73514:12)
    at IncomingMessage.<anonymous> (/home/michael/.node_modules/lib/node_modules/truffle/build/cli.bundled.js:73474:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
```

**Comment by TripleSpeeder** [comment]
I'm using truffle-contract version 1.1.11:
```
$ npm list truffle-contract
react-box@0.1.0 /home/michael/projects/StandingOrderDapp
└── truffle-contract@1.1.11 
```

**Comment by sulliwane** [comment]
you may have forgot to add the ```value: web3.toHex(value)``` parameter to the object input of web3.eth.estimateGas function...you need it if the function called in the contract is payable (note: this is specific to Parity, Geth will not check the value when estimating the transaction cost)
