### ISSUE TITLE
invalid address after calling in JS a solidity (write) function. 

### ISSUE THREAD

**Issue by janterlaak** [trufflesuite/truffle-contract#7]
Default address is not set by contract.deployed(). This will result in a invalid address error when calling a solidity function with a state change from JS. Like writing to a solidity variable. Work around is to set the default address manually in JS. In the truffle 3 console it works ok. It needs something like this web3.eth.defaultAccount = web3.eth.accounts[0] .

**Comment by janterlaak** [comment]
var inputAddressFormatter = function (address) {
    var iban = new Iban(address);
    if (iban.isValid() && iban.isDirect()) {
        return '0x' + iban.address();
    } else if (utils.isStrictAddress(address)) {
        return address;
    } else if (utils.isAddress(address)) {
        return '0x' + address;
    }
    throw new Error('invalid address');  <========================================<
};

**Comment by janterlaak** [comment]
Solidity:
pragma solidity ^0.4.4;
contract Mycontract {
  uint public value;
  event ValueSet(uint val);
  function setValue(uint val) {
    value = val;
    ValueSet(value);
  }
  function getValue() constant returns (uint) {
    return value;
  }
}
/////// Javascript ////////
var provider = new Web3.providers.HttpProvider("http://localhost:8545");
var Mycontract = contract(MyJson);  // from truffle generated Mycontract.json file
Mycontract.deployed().then(function(instance)
{
  instance.setValue(1).then(function(result) {    //FAILS //
    console.log("test");
    console.log(result);
  });
});


Uncaught (in promise) Error: invalid address
    at inputAddressFormatter (http://localhost:3000/static/js/bundle.js:108036:12)
    at inputTransactionFormatter (http://localhost:3000/static/js/bundle.js:107862:21)
    at http://localhost:3000/static/js/bundle.js:108162:29
    at Array.map (native)
    at Method.formatInput (http://localhost:3000/static/js/bundle.js:108161:33)
    at Method.toPayload (http://localhost:3000/static/js/bundle.js:108187:24)
    at Eth.send [as sendTransaction] (http://localhost:3000/static/js/bundle.js:108212:31)
    at SolidityFunction.sendTransaction (http://localhost:3000/static/js/bundle.js:110739:16)
    at SolidityFunction.execute (http://localhost:3000/static/js/bundle.js:110822:38)
    at http://localhost:3000/static/js/bundle.js:88905:17
inputAddressFormatter @ formatters.js:271
inputTransactionFormatter @ formatters.js:97
(anonymous) @ method.js:89
Method.formatInput @ method.js:88
Method.toPayload @ method.js:114
send @ method.js:139
SolidityFunction.sendTransaction @ function.js:136
SolidityFunction.execute @ function.js:219
(anonymous) @ contract.js:188
(anonymous) @ contract.js:154

**Comment by janterlaak** [comment]
Solved; when using .then we need to set a default account explicitly. 
Mycontract.defaults({
  from: web3.eth.accounts[0]
})
