### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by x13machine** [trufflesuite/truffle-contract#84]
### Error
```
TypeError: Cannot read property 'apply' of undefined
    at Provider.sendAsync (/home/brandan/node_modules/truffle-contract/contract.js:23:35)
    at RequestManager.sendAsync (/home/brandan/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:80:19)
    at Object.get [as getNetwork] (/home/brandan/node_modules/truffle-contract/node_modules/web3/lib/web3/property.js:116:33)
    at /home/brandan/node_modules/truffle-contract/contract.js:487:27
    at Promise (<anonymous>)
    at Function.detectNetwork (/home/brandan/node_modules/truffle-contract/contract.js:478:14)
    at TruffleContract.contract.then (/home/brandan/node_modules/truffle-contract/contract.js:404:21)
    at Object.<anonymous> (/home/brandan/grava/tests/mine.js:8:30)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3

```

### Code:
```
var config = require('./config.json')
var Web3 = require('web3');
var web3 = new Web3();
var provider = new Web3.providers.HttpProvider("http://localhost:9545");
var contract = require("truffle-contract");
var gravastar = contract(config);
gravastar.setProvider(provider);

gravastar.at(config.address).then(function(instance) {
	console.log(intance.balances)
}).catch(function(err) {
	console.log(err);
});
```

**Comment by cgewecke** [comment]
@x13machine It means that you're trying to use Web3 1.0 and Truffle hasn't completely integrated that package yet because it's still in beta and has lots of breaking changes. There's good discussions about way's around this in the issues here at:
+ #56
+ #57

Thanks for opening - closing as duplicate.
