### ISSUE TITLE
Uncatchable promise rejection when using at(), await and an address containing no code

### ISSUE THREAD

**Issue by roderik** [trufflesuite/truffle-contract#88]
I'm being hit by wrong user input and no way to capture it nicely.

A user gives me an address, and I run `try { await  Token.at(address)} catch (error){ //something }`. Resulting in an unhandled rejection error as follows.

```
Error: Cannot create instance of Token; no code at address 0xc10c5e0d5367d7374e185214884307ab4c7a4f84
    at Object.callback (/Users/roderik/Development/mint/mint-dapi/components/lib-ethereum/node_modules/truffle-contract/contract.js:412:31)
    at /Users/roderik/Development/mint/mint-dapi/components/lib-ethereum/node_modules/web3/lib/web3/method.js:142:25
    at /Users/roderik/Development/mint/mint-dapi/components/lib-ethereum/node_modules/web3/lib/web3/requestmanager.js:89:9
    at /Users/roderik/Development/mint/mint-dapi/components/lib-ethereum/node_modules/web3-provider-engine/index.js:149:9
    at /Users/roderik/Development/mint/mint-dapi/components/lib-ethereum/node_modules/async/internal/once.js:12:16
    at replenish (/Users/roderik/Development/mint/mint-dapi/components/lib-ethereum/node_modules/async/internal/eachOfLimit.js:59:25)
    at iterateeCallback (/Users/roderik/Development/mint/mint-dapi/components/lib-ethereum/node_modules/async/internal/eachOfLimit.js:49:17)
    at /Users/roderik/Development/mint/mint-dapi/components/lib-ethereum/node_modules/async/internal/onlyOnce.js:12:16
    at resultObj.id (/Users/roderik/Development/mint/mint-dapi/components/lib-ethereum/node_modules/web3-provider-engine/index.js:129:9)
    at /Users/roderik/Development/mint/mint-dapi/components/lib-ethereum/node_modules/async/internal/withoutIndex.js:9:16
```

The code is at https://github.com/trufflesuite/truffle-contract/blob/8686600af7c48712ca4d4ee751cfccfd801eab4a/contract.js#L418

**Comment by nosuchip** [comment]
As temporary workaround you can check is there contract code at specified addrerss:
```
  const code = await web3.eth.getCode(address);

  if (!code || code === '0x0' || code === '0x') throw Error('Not a contract address');

  const contract = TruffleContract(artifacts);

```
